Added scripts, modified requirements, added subpackages
gaborvecsei/Somnium-Doctrina pull request #2
Opened 2018-09-11 20:54 UTC by csxeba

2018-09-17 18:48 UTC, gaborvecsei commented on README.md
> +pip install https://github.com/csxeba/grund
If we use Python3 it should be `pip3 install git+https://github.com/csxeba/grund.git`

2018-09-17 18:50 UTC, gaborvecsei commented on requirements.txt
> +https://github.com/csxeba/grund
Syntax here is almost the same as in the readme: `git+https://github.com/csxeba/grund.git#egg=grund`

https://pip.readthedocs.io/en/1.1/requirements.html

2018-09-17 18:51 UTC, gaborvecsei requested changes
Nice start!!! 💯

Just a few minor changes requested

2018-09-20 05:21 UTC, csxeba commented
Done and done!

2018-09-20 06:48 UTC, gaborvecsei approved these changes

2018-09-20 06:49 UTC, gaborvecsei commented
You can **Squash & Merge** 👍

2018-09-20 10:32 UTC, merged

2018-09-20 10:33 UTC, csxeba commented
Didn't squash tho